### ISSUE TITLE
Getting an error of missing required files when deploying it on kubernetes cluster

### ISSUE THREAD

**Issue by NehaShipt** [hypnoglow/helm-chart-osrm#7]
I am deploying this chart on kubernetes using helm and terraform and using gcs as source of map files . Map-downloader container cameup and running successfully but osrm is not coming up.checked the config maps and logs but did not get anything specific other than the missing files error.

below is my values.yaml:
weightedRule: ${weighted_rule}
fullnameOverride: ${fullname_override}
namespace: "osrm"
serviceAccountEmail: ${service_account_email}
replicaCount: ${replica_count}
cluster:
  domain: ${cluster_domain}
  tlsCertSecret: ${cluster_tls_secret_name}
persistence:
  size: ${storage_size_gibibytes}
map: 
  source: gcs
  gcs: 
    uri: ${gcs_uri}

passing all the values in locals file.
Am i missing something here?

**Comment by hypnoglow** [comment]
It's not a lot info to understand what's going on in your deployment.

Could you check the events in your pod? Or the logs from the container?
