### ISSUE TITLE
Multiple Profile support (foot, driving, bicycle etc)

### ISSUE THREAD

**Issue by ferhatguneri** [hypnoglow/helm-chart-osrm#9]
I would suggest having a parameter which will help user to choose which profile to extract. Since OSRM does not support multiple profiles i was thinking deploying 2 different helm charts one for driving the other for walking distance. I tried to find init container script but couldn't find it. Could you please help to create new parameter for choosing profile?

**Comment by ferhatguneri** [comment]
I just saw [pzelensky](https://github.com/pzelensky) already created the change. Could you please help to approve?

https://github.com/hypnoglow/helm-chart-osrm/pull/6

**Comment by hypnoglow** [comment]
Fixed in #6
